[aliases]
brown_noise = "ffplay -hide_banner -loglevel error -nodisp -f lavfi 'anoisesrc=color=brown:amplitude=0.354,lowpass=f=550:poles=1,bass=g=12:f=60,afade=t=in:d=3'"
cat = "bat"
exit_0 = "/home/vaishnav/Desktop/My_Projects/exit_0/scripts/welcome_menu.sh"
ff = "fastfetch"
ga = "git add"
gd = "git diff"
ghpr = "gh pr create"
gs = "git status"
ll = "eza -lah --icons --hyperlink"
localsend = "handlr open https://web.localsend.org/"
ls = "eza --icons --hyperlink"
man = "batman"
nchat_tg = "nchat -d ~/.config/nchat_tg"
pdf = "papers"
preview_md = "gh markdown-preview"
project = "cd /home/vaishnav/Desktop/My_Projects/"
starting_soon = "mpv --fs=yes --osc=no /home/vaishnav/Desktop/My_Projects/starting_soon.gif --loop"
tree = "eza --icons --hyperlink --tree"
webcam = "mpv --fs=yes --osc=no av://v4l2:/dev/video0 --profile=low-latency --untimed --demuxer-lavf-o=input_format=mjpeg > /dev/null 2>&1"
zephyr_venv = "source /home/vaishnav/zephyrproject/zephyr_venv/bin/activate"

[shell]

[logging]
