active_profiles = []

[aliases]
cat = "bat"
exit_0 = "/home/vaishnav/Desktop/My_Projects/exit_0/scripts/welcome_menu.sh"
ff = "fastfetch"
ga = "git add"
gd = "git diff"
gs = "git status"
ll = "eza -lah --icons --hyperlink"
ls = "eza --icons --hyperlink"
nchat_tg = "nchat -d ~/.config/nchat_tg"
pdf = "papers"
preview_md = "gh markdown-preview"
project = "cd /home/vaishnav/Desktop/My_Projects/"
tree = "eza --icons --hyperlink --tree"
webcam = "mpv av://v4l2:/dev/video0 --profile=low-latency --untimed --demuxer-lavf-o=input_format=mjpeg > /dev/null 2>&1"
