[v1]
"alacritty 0.15.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"codeberg-cli 0.4.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["berg"]
"eva 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["eva"]
"evcxr_jupyter 0.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["evcxr_jupyter"]
"eza 0.20.23 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"fd-find 10.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"koji 3.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["koji"]
"mdbook 0.4.47 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"mdcat 2.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdcat"]
"neovide 0.14.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["neovide"]
"nu 0.103.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu"]
"onefetch 2.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["onefetch"]
"sd 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"serie 0.4.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["serie"]
"skim 0.16.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"zellij 0.42.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
