return {
  {
    "monok-robeto/nvim.sfx_player",
    event = "VeryLazy",
    config = function()
      require("nvim.sfx_player").setup({
        title = "nvim.sfx_player",
        mpv_path = "mpv",
        ffprobe_path = "ffprobe",
        default_volume = 100,
        volume_step = 5,
        seek_step = 3,
        loop_default = false,
        update_interval = 200,
        bar_width = 34,
        border = "rounded",
        auto_close_on_leave = true,
        window = {
          width = nil,
          row = nil,
          col = nil,
        },
        icons = {
          file = "🎵",
          paused = "▶",
          playing = "⏸",
          volume = "🔊",
          loop_on = "🔁",
          loop_off = "➡",
        },
        extensions = {
          "mp3",
          "wav",
          "flac",
          "ogg",
          "oga",
          "opus",
          "m4a",
          "aac",
          "wma",
          "aiff",
          "aif",
          "alac",
          "ape",
          "mka",
        },
        keymaps = {
          play_pause = "<Space>",
          seek_forward = "<Right>",
          seek_backward = "<Left>",
          volume_up = "<Up>",
          volume_down = "<Down>",
          toggle_loop = "L",
          quit = { "<Esc>", "q" },
        },
        highlights = {
          title = { link = "Title" },
          name = { link = "Title" },
          meta = { link = "Comment" },
          icon = { link = "Special" },
          filled = { link = "Statement" },
          knob = { link = "Special" },
          remain = { link = "Comment" },
          time = { link = "Number" },
          volume = { link = "Number" },
          loop_active = { link = "String" },
          loop_inactive = { link = "Comment" },
          help = { link = "NonText" },
        },
      })
    end,
  },
}
