language: rust
dist: bionic
addons:
   apt:
      packages:
         - libssl-dev
rust:
  - stable
  - nightly
#   - 1.44.1

jobs:
  fast_finish: true

cache: cargo

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

script:
  - echo rust version is "$TRAVIS_RUST_VERSION"
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then echo running with sanitizer; RUSTFLAGS="-Z sanitizer=address" cargo run --example arc-sanitize --target x86_64-unknown-linux-gnu; else echo not running on nightly so skipping sanitizer; fi
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

notifications:
  email:
    on_success: never
